/*
  CYBERSHOP - PRODUCTOS Y CONFIGURACIÓN

  IMPORTANTE:
  1) Cambia whatsappNumber por tu número con indicativo de país, sin + ni espacios.
     Ejemplo Colombia: "573001112233"

  2) El logo principal debe estar en la raíz con este nombre:
     logo-cybershop.png

  3) La imagen grande de logos debe estar en la raíz con este nombre:
     logos-cybershop-transparente.png

  4) Los logos individuales deben estar dentro de la carpeta:
     /logos/

  5) Para cambiar precios, modifica únicamente el valor "precio".
*/

const CONFIG = {
  tienda: "CyberShop",
  whatsappNumber: "57TU_NUMERO_AQUI",
  logoUrl: "logo-cybershop.png",
  logosStripUrl: "logos-cybershop-transparente.png",
  mensajeBase: "Hola estoy interesado en",
};

const productos = [
  {
    nombre: "Netflix",
    categoria: "Streaming",
    precio: 15000,
    precioAnterior: 20000,
    logo: "./logos/Netflix.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Netflix Privado",
    categoria: "Streaming",
    precio: 21900,
    precioAnterior: 28000,
    logo: "./logos/Netflix.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Disney + Star ESPN",
    categoria: "Streaming",
    precio: 14000,
    precioAnterior: 20000,
    logo: "./logos/Disney.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Amazon Prime Video",
    categoria: "Streaming",
    precio: 8000,
    precioAnterior: 12000,
    logo: "./logos/Amazon.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "HBO MAX",
    categoria: "Streaming",
    precio: 9000,
    precioAnterior: 15000,
    logo: "./logos/HBO.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "IPTV Win+ 3000 Canales",
    categoria: "IPTV",
    precio: 15000,
    precioAnterior: 22000,
    logo: "./logos/IPTV.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Plex",
    categoria: "Streaming",
    precio: 15000,
    precioAnterior: 20000,
    logo: "./logos/Plex.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Crunchyroll",
    categoria: "Streaming",
    precio: 9000,
    precioAnterior: 14000,
    logo: "./logos/Crunchyr.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Paramount",
    categoria: "Streaming",
    precio: 9000,
    precioAnterior: 14000,
    logo: "./logos/Paramount.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Vix",
    categoria: "Streaming",
    precio: 8000,
    precioAnterior: 12000,
    logo: "./logos/Vix.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Spotify 1 Mes",
    categoria: "Música",
    precio: 12000,
    precioAnterior: 18000,
    logo: "./logos/Spotify.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Spotify 3 Meses",
    categoria: "Música",
    precio: 33000,
    precioAnterior: 45000,
    logo: "./logos/Spotify.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Youtube 1 Mes",
    categoria: "Streaming",
    precio: 12000,
    precioAnterior: 18000,
    logo: "./logos/Youtube.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Youtube 3 Meses",
    categoria: "Streaming",
    precio: 33000,
    precioAnterior: 45000,
    logo: "./logos/Youtube.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Canva Pro 1 Mes",
    categoria: "Diseño",
    precio: 10000,
    precioAnterior: 15000,
    logo: "./logos/Canva.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Canva Pro 3 Meses",
    categoria: "Diseño",
    precio: 25000,
    precioAnterior: 35000,
    logo: "./logos/Canva.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "CapCut Pro 1 Mes",
    categoria: "Diseño",
    precio: 25000,
    precioAnterior: 35000,
    logo: "./logos/Capcut.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Office 365 1 Mes",
    categoria: "Productividad",
    precio: 10000,
    precioAnterior: 15000,
    logo: "./logos/Office.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Office 365 12 Meses",
    categoria: "Productividad",
    precio: 99000,
    precioAnterior: 130000,
    logo: "./logos/Office.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Xbox Game Pass Ultimate 1 Mes",
    categoria: "Gaming",
    precio: 35000,
    precioAnterior: 45000,
    logo: "./logos/Xbox.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Chat GPT Plus 1 Mes",
    categoria: "IA",
    precio: 35000,
    precioAnterior: 45000,
    logo: "./logos/GPT.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Chat GPT Plus 3 Meses",
    categoria: "IA",
    precio: 90000,
    precioAnterior: 120000,
    logo: "./logos/GPT.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Perplexity AI Pro 1 Mes",
    categoria: "IA",
    precio: 30000,
    precioAnterior: 40000,
    logo: "./logos/Perplexity.png",
    destacado: true,
    stockLimitado: false,
  },
  {
    nombre: "Gemini AI Pro con VEO 1 Mes",
    categoria: "IA",
    precio: 40000,
    precioAnterior: 55000,
    logo: "./logos/Gemini.png",
    destacado: true,
    stockLimitado: false,
  },

  // OFERTAS
  {
    nombre: "IPTV Canales Deportivos 3 Meses",
    categoria: "Ofertas",
    precio: 30000,
    precioAnterior: 45000,
    logo: "./logos/IPTV.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Spotify 4 Meses",
    categoria: "Ofertas",
    precio: 40000,
    precioAnterior: 55000,
    logo: "./logos/Spotify.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Xbox Game Pass Ultimate 2 Meses",
    categoria: "Ofertas",
    precio: 55000,
    precioAnterior: 70000,
    logo: "./logos/Xbox.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Google Gemini AI Pro 3 Meses",
    categoria: "Ofertas",
    precio: 90000,
    precioAnterior: 120000,
    logo: "./logos/Gemini.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Google Gemini AI Pro 12 Meses",
    categoria: "Ofertas",
    precio: 250000,
    precioAnterior: 320000,
    logo: "./logos/Gemini.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Amazon Prime Video 6 Meses",
    categoria: "Ofertas",
    precio: 25000,
    precioAnterior: 48000,
    logo: "./logos/Amazon.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "HBO MAX 3 Meses",
    categoria: "Ofertas",
    precio: 25000,
    precioAnterior: 40000,
    logo: "./logos/HBO.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Crunchyroll 3 Meses",
    categoria: "Ofertas",
    precio: 20000,
    precioAnterior: 30000,
    logo: "./logos/Crunchyr.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Office 365 12 Meses",
    categoria: "Ofertas",
    precio: 80000,
    precioAnterior: 99000,
    logo: "./logos/Office.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "CapCut Pro 3 Meses",
    categoria: "Ofertas",
    precio: 50000,
    precioAnterior: 75000,
    logo: "./logos/Capcut.png",
    destacado: true,
    stockLimitado: true,
  },
  {
    nombre: "Vix 3 Meses",
    categoria: "Ofertas",
    precio: 15000,
    precioAnterior: 24000,
    logo: "./logos/Vix.png",
    destacado: true,
    stockLimitado: true,
  },
];
